### ISSUE TITLE
Booking page

### ISSUE THREAD

**Issue by Meyaal** [Meyaal/Dine#5]
As a Customer I** can click on a booking page** so that I** can make my reservation** at the restaurant

### Approval Requirements

- Display a booking link on hero section.
- Display a booking link in the navbar for easy access.
- Display booking options to Customer, based on guests, date and time.
- Display a pop-up message to confirm booking.

### Tasks

- [ ] Create the booking link in the hero page
- [ ] Create the booking link in the navbar
- [ ] Create the bookings model
- [ ] Create the views function for the bookings page
- [ ] Create the bookings page HTML & CSS
