### ISSUE TITLE
Manage Booking

### ISSUE THREAD

**Issue by Meyaal** [Meyaal/Dine#8]
As a Customer **I can click on "my booking page"** so that **I can make changes to** my bookings at the restaurant

### Approval Requirements:

* Display a my bookings link in the navbar for easy access.
* Display a list of all the bookings and a link to delete or update the booking.
* Display a pop-up message to confirm changes.

### Tasks:

- [ ] Create the my booking link in the navbar
- [ ] Create the my bookings model
- [ ] Create the views function for the my bookings page
- [ ] Create the my bookings page HTML & CSS
